services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: server_c
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client_c
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - server