services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_c
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_c
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules