import json
from typing import Any
from lib.types import HistoryRecordDict
from lib.db import get_supabase


def serialize_for_db(obj: Any) -> Any:
    """Custom serializer to handle File objects and other non-JSON serializable types."""
    # Handle File objects (FastAPI UploadFile or similar)
    if hasattr(obj, "filename") and hasattr(obj, "content_type"):
        return {
            "filename": getattr(obj, "filename", "unknown"),
            "content_type": getattr(obj, "content_type", "unknown"),
            "size": getattr(obj, "size", None),
            "type": "file",
        }
    # Handle Pydantic models
    elif hasattr(obj, "model_dump"):
        try:
            return obj.model_dump(mode="json")
        except Exception:
            # Fallback to dict conversion
            return obj.model_dump()
    # Handle dictionaries
    elif isinstance(obj, dict):
        return {k: serialize_for_db(v) for k, v in obj.items()}
    # Handle lists
    elif isinstance(obj, list):
        return [serialize_for_db(item) for item in obj]
    # Handle other non-serializable objects
    elif hasattr(obj, "__dict__"):
        return serialize_for_db(obj.__dict__)
    else:
        # For primitive types and anything else
        try:
            json.dumps(obj)  # Test if it's JSON serializable
            return obj
        except TypeError:
            return str(obj)  # Convert to string as fallback


async def get_saved_records(user_id: str) -> list[HistoryRecordDict]:
    """Retrieve all history records for a given user, ordered by creation time desc."""
    client = await get_supabase()
    res = await (
        client.table("history")
        .select("*")
        .eq("user_id", user_id)
        .order("created_at", desc=True)
        .execute()
    )
    return res.data or []


async def save_record(record: HistoryRecordDict) -> HistoryRecordDict:
    """Insert a new history record and return the created row."""
    client = await get_supabase()

    try:
        # Validate the record first
        HistoryRecordDict.validate_input(record)

        # Deep serialize the entire record to handle any File objects
        serialized_record = serialize_for_db(record)

        # Ensure the record matches the expected schema
        if not isinstance(serialized_record, dict):
            raise ValueError("Record must be a dictionary")

        # Validate required fields are present (id might be auto-generated by DB)
        required_fields = ["user_id", "name", "input_type", "input", "output"]
        for field in required_fields:
            if field not in serialized_record:
                raise ValueError(f"Missing required field: {field}")

        # Add created_at if not present
        if "created_at" not in serialized_record:
            from datetime import datetime

            serialized_record["created_at"] = datetime.utcnow().isoformat()

        print(f"Serialized record for DB: {json.dumps(serialized_record, indent=2)}")

        res = await client.table("history").insert(serialized_record).execute()

        if not res.data:
            raise ValueError("Failed to insert record - no data returned")

        return res.data[0] if isinstance(res.data, list) else res.data

    except Exception as e:
        print(f"Error in save_record: {str(e)}")
        print(f"Record type: {type(record)}")
        print(f"Record contents: {record}")
        raise e


async def rename_saved_record(
    history_id: str, user_id: str, new_name: str
) -> HistoryRecordDict:
    """Rename the 'name' field of a specific history record and return the updated row."""
    client = await get_supabase()
    res = await (
        client.table("history")
        .update({"name": new_name})
        .eq("id", history_id)
        .eq("user_id", user_id)
        .execute()
    )

    if not res.data:
        raise ValueError(f"History record {history_id} not found for user {user_id}")

    return res.data[0] if isinstance(res.data, list) else res.data


async def delete_saved_record(history_id: str, user_id: str) -> None:
    """Delete a specific history record for a user."""
    client = await get_supabase()
    res = await (
        client.table("history")
        .delete()
        .eq("id", history_id)
        .eq("user_id", user_id)
        .execute()
    )
    if not res.data:
        raise ValueError(f"History record {history_id} not found for user {user_id}")
